apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: green-rollout
  namespace: skills
  labels:
    app: green
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: green
  template:
    metadata:
      labels:
        app: green
    spec:
      terminationGracePeriodSeconds: 30
      nodeSelector:
        kubernetes.io/os: linux
        eks.amazonaws.com/nodegroup: gj2025-eks-app-nodegroup
      containers:
      - name: green
        image: 571480186401.dkr.ecr.ap-northeast-2.amazonaws.com/green:20250913033428
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: db-secret
        ports:
        - containerPort: 8080
  strategy:
    blueGreen:
      activeService: green-service
      autoPromotionEnabled: true

 
